### ISSUE TITLE
Compile Error for RPi3 32-bit

### ISSUE THREAD

**Issue by Bones558** [lplassman/FFMPEG-NDI#3]
I am unable to get this to compile for a Raspberry Pi 3 A+.
I have included a copy of the log for troubleshooting reference.

(It compiles just fine on a RPi 4 B.)

I am running Raspberry PI OS Bookworm on all.

Thanks for any help.

[ffmgeg-build.log](https://github.com/lplassman/FFMPEG-NDI/files/13881321/ffmgeg-build.log)

**Comment by lplassman** [comment]
I am not really sure where the error is occurring or why it fails at the end. It seems like an incompatibility with the NDI libraries of which I have no control over. It could also be because of running a 32-bit OS. I never actually tested this on a Raspberry Pi 3 because I didn’t have one available. If possible, I would attempt to compile on a 64-bit OS on the Raspberry Pi 3 and see if that solves the problem.

**Comment by Bones558** [comment]
Thanks for replying.

I tried to compile it on a RPi4 with 64-bit Bookworm, it compiled.
When I ran it using your exact examples, NDI receiver sees a stream from the RPi4 but there is no video transmitted, just a black screen.

Any ideas?

**Comment by lplassman** [comment]
Are you trying to stream a camera to NDI? If so, it is probably a format issue on the camera side of things. If FFMPEG isn't able to read the device, no NDI frames will be output.

**Comment by Bones558** [comment]
Yes, I have a Logitech C920 webcam attached to the RPi4.
The camera supports YUVU, MJPEG, & H264 formats.

Based on your command:
"ffmpeg -f v4l2 -framerate 30 -video_size 1280x720 -pixel_format mjpeg -i /dev/video1 -f libndi_newtek -pix_fmt uyvy422 CameraOut"

I've tried changing the settings for both MJPEG and H264, 1280x720 and 1920x1080, framerate 30 and 60, no combination works, just black.

**Comment by Bones558** [comment]
If it helps, I also tried your other project "V4L2 to NDI" but I also get just a black output there.

Both have been built on a fresh SD card loaded with Bookwork 64-bit for RPi4 to ensure nothing random remained.
I tried building with the written image on the SD card as well as updating all packages before building, same result.

As another test I also have a "generic" webcam with no branding.
v4l2-ctl reports it supports MJPEG and YUYV.
This generic camera has the same output, black screen when tried with either project.

**Comment by lplassman** [comment]
That is strange. I wonder if it is some incompatibility with Raspberry Pi OS Bookworm and the NDI libraries. They haven't been updated to support the new version of linux yet. I will check a few other things from my end as well, but I am thinking that is the problem.

**Comment by Bones558** [comment]
So going off your theory of OS issues...

I decided to try another OS, but I went lateral instead of downgrading...
I flashed Ubuntu for RaspberryPi, Server 22.04.3 LTS 64-bit, applying all package updates, to my RPi4.

You project built successfully, and I am able to stream using NDI from the attached webcam.

I'll test on the RPi3A+ with Ubuntu tomorrow to see if it will build or not, since that was my original issue.

**Comment by lplassman** [comment]
Awesome! Glad it works now! I will have to update my tools once NDI updates their libraries for the new OS release of Bookworm.

**Comment by Bones558** [comment]
Ok, results for the RPi3A+...

It won't compile on that board. 
I believe it is a RAM limitation issue as those boards only have 512MB.

If I compile on a RPi4 and copy to the RPi3A+ ffmpeg will run.

**Comment by Bones558** [comment]
Another interesting finding, this one is no matter what device ffmpeg with NDI is run on.

A NDI source is seen by the receiver and can be connected to, but no video is transmitted if the sending device is connected via a WiFi connection.
When the sending device is hardwired and the WiFi disabled it works perfectly.
(It didn't matter what type of connection the device receiving the video was on.)

Have you had any experience with NDI sending over WiFi?  Are there any parameters for the NDI library in ffmpeg that can be adjusted to maybe allow this?

**Comment by Bones558** [comment]
Found a resolution for the WiFi issue.
Details can be found here:  https://forum.vizrt.com/index.php?threads/ndi-seen-but-no-video-streamed.253398/
